
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: resurface_development

test:
  <<: *default
  database: resurface_test

production:
  <<: *default
  database: resurface_production
  username: resurface
  password: <%= ENV['RESURFACE_DATABASE_PASSWORD'] %>
